apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: gcp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: my-image
        image: gcr.io/mongy-367814/my-image:latest
        ports:
        - containerPort: 8080
